name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: |
            all/build/MinecraftServerExceptionDiscordSender.jar
            bukkit/build/MinecraftServerExceptionDiscordSender-bukkit.jar
            bungee/build/MinecraftServerExceptionDiscordSender-bungee.jar
            velocity/build/MinecraftServerExceptionDiscordSender-velocity.jar
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Get The Version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: true
          files: '*.jar'
