name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        run: ./gradlew build
      - name: Copy
        run: |
          cp all/build/libs/MinecraftServerExceptionDiscordSender.jar .
          cp bukkit/build/libs/MinecraftServerExceptionDiscordSender-bukkit.jar .
          cp bungee/build/libs/MinecraftServerExceptionDiscordSender-bungee.jar .
          cp velocity/build/libs/MinecraftServerExceptionDiscordSender-velocity.jar .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: '*.jar'
  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build
      - name: Get The Version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: true
          files: '*.jar'
